// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpAhGBF2H4A-y8rOzV9bIbKj-mqWYTtK4',
    appId: '1:140032331236:web:8bd36bea244d6918f9cbf1',
    messagingSenderId: '140032331236',
    projectId: 'guitar-network',
    authDomain: 'guitar-network.firebaseapp.com',
    storageBucket: 'guitar-network.appspot.com',
    measurementId: 'G-VLYQTE49N3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrNi-lv9rR8Lvo_HRlTkY0VajO8GGo5Ss',
    appId: '1:140032331236:android:067d3b29981895caf9cbf1',
    messagingSenderId: '140032331236',
    projectId: 'guitar-network',
    storageBucket: 'guitar-network.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI3ErRqeHbL1JVW13fC9bZF6wCWIidJhs',
    appId: '1:140032331236:ios:40b2a902a3f0afe0f9cbf1',
    messagingSenderId: '140032331236',
    projectId: 'guitar-network',
    storageBucket: 'guitar-network.appspot.com',
    iosClientId: '140032331236-hrtmgings1dhap1gfhbt7df2v1sijlfg.apps.googleusercontent.com',
    iosBundleId: 'com.example.guitarNetworkVkr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI3ErRqeHbL1JVW13fC9bZF6wCWIidJhs',
    appId: '1:140032331236:ios:40b2a902a3f0afe0f9cbf1',
    messagingSenderId: '140032331236',
    projectId: 'guitar-network',
    storageBucket: 'guitar-network.appspot.com',
    iosClientId: '140032331236-hrtmgings1dhap1gfhbt7df2v1sijlfg.apps.googleusercontent.com',
    iosBundleId: 'com.example.guitarNetworkVkr',
  );
}
